version: '3'

services:
  rides-hailing-api:
    build: .
    command: npm run start
    volumes:
      - .:/api
      - /api/node_modules
    ports:
      - ${PORT:-4000}:${PORT:-400}
    environment:
      MONGODB_AUTH_SOURCE: admin
      MONGODB_USERNAME: ${MONGODB_USERNAME}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
      MONGODB_URL: ${MONGODB_URL}/${MONGODB_NAME}
      NODE_ENV: dev
      PORT: ${PORT:-4000}
    depends_on:
      - mongodb
    links:
      - mongodb
  
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_NAME}
    volumes:
      - ./mongodb-data:/data/db
      
volumes:
  mongodb-data: