const IS_EMPTY = "IS_EMPTY";
const INVALID_EMAIL = "INVALID_EMAIL";
const MIN_LENGTH = "MIN_LENGTH";
const INVALID_CAR_STATUS = "INVALID_CAR_STATUS";

module.exports = {
    IS_EMPTY,
    INVALID_EMAIL,
    MIN_LENGTH,
    INVALID_CAR_STATUS,
}